# -*- coding: utf-8 -*-
"""rainfall_curve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-ox5xwVwa72UhocOQ5nu7T_i6HF0uKc
"""

import pandas as pd
import matplotlib.pyplot as plt

def plot_rainfall_curve(data_df, curve_type):
    # Create subplots in a single row
    fig, axs = plt.subplots(1, 1, figsize=(12, 6))

    if curve_type == 'hyetograph':
        # Incremental Rainfall Histogram
        axs.hist(data_df['Time (minutes)'], edgecolor='k', orientation='vertical', weights=data_df['Incremental Rainfall'])
        axs.set_xlabel('Time (minutes)')
        axs.set_ylabel('Rainfall (cm)')
        axs.set_title('Hyetograph')
    elif curve_type == 'intensity-duration curve':
        # Intensity of Rainfall
        axs.plot(data_df['Time (minutes)'], data_df['Intensity of Rainfall'], marker='s', linestyle='-')
        axs.set_xlabel('Time (minutes)')
        axs.set_ylabel('Intensity of Rainfall (cm/h)')
        axs.set_title('Intensity-duration curve')
    elif curve_type == 'mass curve':
        # Cumulative Rainfall
        axs.plot(data_df['Time (minutes)'], data_df['Cumulative Rainfall'], marker='D', linestyle='-')
        axs.set_xlabel('Time (minutes)')
        axs.set_ylabel('Cumulative Rainfall (cm)')
        axs.set_title('Mass Curve')
    else:
        print("Invalid curve type. Please choose from 'Hyetograph', 'Intensity-duration curve', or 'Mass Curve'.")

    # Adjust layout and show the plot
    plt.tight_layout()
    plt.show()

